### ISSUE TITLE
why you abandoned it?

### ISSUE THREAD

**Issue by cocodrino** [brandonbloom/asyncx#2]
hi brandon, I'm curious about what kind of problems you had and why you abandoned the project?..seems an interesting idea..do you have problems with the implementation?..combining clojure async with FRP or did you end thinking than FRP is a bad idea?...

**Comment by brandonbloom** [comment]
Well, for one thing, core.async channels are now transducers-aware, which is what you really should do if you need map, filter, etc for channels. Look for the `xform` arguments.

Beyond that, I've found push-sequence abstractions (to contrast with Elm-style FRP) to be of questionable utility and excessive complexity. However, this is not the appropriate forum for me to write about my viewpoints on this.
